# Machine configuration for the KrazyMP product.
#
# This is a fictitious product. These settings are actually for the
# ZynqMP KRIA KD240 Devres Starter Kit.

require include/common.inc

# Adds "zynqmp" to MACHINEOVERRIDES, and ultimately to OVERRIDES
require conf/machine/include/soc-family.inc
SOC_FAMILY = "zynqmp"

# Defines instruction sets and tunes for the two CPUs in the SoC.
# Microblaze instruction are needed to build the PMUFW.
DEFAULTTUNE ?= "cortexa53"
TUNEFILE[cortexa53] = "conf/machine/include/arm/armv8a/tune-cortexa53.inc"
TUNEFILE[microblaze] = "conf/machine/include/microblaze/tune-microblaze.inc"
TUNEFILE = "${@d.getVarFlag('TUNEFILE', d.getVar('DEFAULTTUNE'))}"
require ${TUNEFILE}

# Set ZynqMP microblaze multiconfig to build PMUFW
BBMULTICONFIG = "zynqmp-microblaze"

# Basic info about the hardware
MACHINE_FEATURES = "apm usbgadget usbhost alsa"
SERIAL_CONSOLES = "115200;ttyPS1"

PMUFW_EXTRA_CFLAGS = "-DK24_SOM"

# Select bootloader recipe, set parameters for bootloader build
TFA_PLATFORM = "zynqmp"
TFA_BUILD_TARGET = "bl31"
TFA_EXTRA_OEMAKE = "RESET_TO_BL31=1 ZYNQMP_CONSOLE=cadence1"

# Select bootloader recipe, set parameters for bootloader build
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-kiss"
UBOOT_MACHINE = "xilinx_zynqmp_kria_defconfig"
UBOOT_MAKE_TARGET = " DEVICE_TREE=zynqmp-smk-k24-revA-sck-kd-g-revA"
SPL_BINARY = ""
UBOOT_SUFFIX = "dtb"
UBOOT_ELF = "u-boot"
UBOOT_LOADADDRESS = "0x18000000"
UBOOT_ENTRYPOINT = "0x18000000"
UBOOT_DTB_LOADADDRESS = "0x40000000"

# Set configuration for extlinux file
UBOOT_EXTLINUX_CONSOLE = "console=ttyPS1,115200"
UBOOT_EXTLINUX_FDT = "../zynqmp-smk-k24-revA-sck-kd-g-revA.dtb"
UBOOT_EXTLINUX_ROOT = "root=/dev/sda1"

# Build boot.bin image
EXTRA_IMAGEDEPENDS += "bootbin-xilinx"

# Select kernel recipe, set parameters for kernel build
PREFERRED_PROVIDER_virtual/kernel = "linux-kiss"
KERNEL_DEVICETREE = "xilinx/zynqmp-smk-k24-revA-sck-kd-g-revA.dtb"
KERNEL_IMAGETYPE = "Image"
