DISTROOVERRIDES = "firmware"

DEFAULTTUNE = "microblaze"
TUNE_FEATURES = "microblaze v9.2 barrel-shift pattern-compare reorder fpu-soft"

TCLIBC = "newlib"
LINKER_HASH_STYLE:libc-newlib = ""
LIBC_DEPENDENCIES:append = " newlib-staticdev libgloss-staticdev"

DISABLE_STATIC:class-target ?= ""

require conf/distro/include/no-static-libs.inc
require conf/distro/include/yocto-uninative.inc
INHERIT += "uninative"

TMPDIR:append = "_microblaze"
