# Use microblaze architecture
DEFAULTTUNE = "microblaze"
TUNE_FEATURES = "microblaze v9.2 barrel-shift pattern-compare reorder fpu-soft"

# Use newlib baremetal C library
TCLIBC = "newlib"

# Fix: ld: unrecognized option '--hash-style=sysv'
LINKER_HASH_STYLE:libc-newlib = ""

# Include static C library (newlib) and syscall stubs (libgloss) for bare-metal builds
LIBC_DEPENDENCIES:append = " newlib-staticdev libgloss-staticdev"

# Allow static libraries for target builds
DISABLE_STATIC:class-target ?= ""

# Include distro-level static library and uninative configurations
require conf/distro/include/no-static-libs.inc
require conf/distro/include/yocto-uninative.inc
INHERIT += "uninative"

# Isolate build directory for this multiconfig
TMPDIR:append = "_microblaze"
