COMPATIBLE_MACHINE:stompduck = "^stompduck$"
COMPATIBLE_MACHINE:freiheit93 = "^freiheit93$"

# trusted-firmware-a can depend on "u-boot", we have "u-boot-kiss"
# Here the dependency is only needed for stompduck. Freiheit93 also use
# trusted-firmware-a, but its binary is embedded in an image generated by
# u-boot: the dependency is the other way around.
DEPENDS:append:stompduck = " virtual/bootloader optee-os"
