# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-kiss-advanced"
BBFILE_PATTERN_meta-kiss-advanced = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-kiss-advanced = "9"

LAYERDEPENDS_meta-kiss-advanced = "core meta-arm meta-kiss"
LAYERSERIES_COMPAT_meta-kiss-advanced = "scarthgap"
